name: conditional_trigger
description: Make it easier for you to set the conditions (such as min days or min calls) for specific method or widget.
version: 0.1.0
homepage: https://github.com/vnniz/conditional_trigger

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^4.1.0
  satisfied_version: ^0.3.0
  shared_preferences: ^2.2.1
  update_helper: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
